<a href="https://colab.research.google.com/github/charfx/learning_pytorch_deep_learning/blob/main/first_steps_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [8]:
mu_list=[1,2,3,4,5]

In [9]:
onees=np.ones(shape=(4,5))

# Tensor :
  

In [25]:
tensor_2d=torch.randn(3,4)

In [26]:
tensor_2d

tensor([[ 0.0350, -0.0161,  1.6530,  2.3174],
        [-1.1719,  0.0830,  0.0377, -1.2984],
        [-0.2830, -1.9745, -1.4212, -0.9065]])

In [27]:
tensor_2d.type()

'torch.FloatTensor'

In [28]:
#creating of tensor based of the numpy array

second_t=torch.tensor(onees)

In [40]:
mytorch=torch.arange(15)
mytorch.size()

torch.Size([15])

In [42]:
mytorch_reshaped=mytorch.reshape(3,5)
mytorch_reshaped

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [43]:
mytorch_reshaped.shape

torch.Size([3, 5])

# Some Maths with torch

In [45]:
tensor_a=torch.tensor([1,2,3,4,5])
tensor_b=torch.tensor([1,2,3,4,5])

In [52]:
tensor_z=tensor_a * tensor_b
tensor_z

tensor([ 1,  4,  9, 16, 25])

In [53]:
torch.add(tensor_a,tensor_b)

tensor([ 2,  4,  6,  8, 10])

In [60]:
torch.var(tensor_a.float())

tensor(2.5000)

# first neural network